import Link from "next/link";
import type { Metadata } from "next";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing use of the Saksham website and admin dashboard.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12">
      <Link href="/" className="mb-8 inline-flex items-center gap-1.5 text-sm text-foreground-dim hover:text-brand">
        <ArrowLeft className="h-4 w-4" />
        Back to Saksham
      </Link>

      <h1 className="text-3xl font-semibold">Terms of Service</h1>
      <p className="mt-1 text-sm text-foreground-faint">Last updated: September 2026</p>

      <div className="mt-6 rounded-md border border-warning/25 bg-warning-soft p-4 text-sm text-warning">
        This is a good-faith draft, not a substitute for legal review before real-world deployment.
      </div>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground">
        <section>
          <h2 className="text-lg font-semibold">1. What this site is</h2>
          <p className="mt-2 text-foreground-dim">
            This website is an informational overview of Saksham — a prototype voice-first assistant that helps
            beneficiaries under the PM-AJAY scheme describe a traditional skill and find a matching NSQF
            qualification and nearby government training programme — plus a restricted admin dashboard for programme
            staff to monitor activity. The beneficiary-facing assistant itself runs on the separate Saksham mobile
            app and WhatsApp channel, not on this website.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">2. Not official government advice</h2>
          <p className="mt-2 text-foreground-dim">
            Figures and statistics shown here and in the admin dashboard are generated by an AI matching process
            against a real government dataset, but represent suggestions and aggregate activity, not guarantees of
            eligibility, enrolment, or certification. Some fields on training programmes (exact seat counts, contact
            numbers, batch dates) are illustrative sample data, as no government source currently publishes those
            centrally — this is disclosed on the homepage.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">3. Admin accounts</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-foreground-dim">
            <li>Admin dashboard access is restricted to authorized Ministry of Social Justice &amp; Empowerment staff.</li>
            <li>You&apos;re responsible for keeping your admin password confidential.</li>
            <li>Beneficiary data shown in the dashboard must only be used for programme administration, never shared or exported for unrelated purposes.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">4. Acceptable use</h2>
          <p className="mt-2 text-foreground-dim">Don&apos;t use this site to:</p>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-foreground-dim">
            <li>Attempt to overwhelm, scrape at scale, or reverse-engineer the service, including automated/scripted requests to its API endpoints.</li>
            <li>Attempt to access the admin dashboard without authorization.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">5. No warranty</h2>
          <p className="mt-2 text-foreground-dim">
            This is prototype software provided as-is, for demonstration of the PM-AJAY skilling concept. It may be
            unavailable, incomplete, or contain errors. We make reasonable efforts to keep the underlying government
            datasets accurate and up to date but do not guarantee completeness or real-time accuracy.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">6. Changes</h2>
          <p className="mt-2 text-foreground-dim">
            We may update these terms as the product evolves. Continued use after a change means you accept the
            updated terms.
          </p>
        </section>
      </div>
    </main>
  );
}
